# -*- coding: utf-8 -*-
"""日常词表独有词汇的音节切分与词根助记。

格式与 phon.py 完全一致：值是 (音节串, 助记) 二元组，
音节串写成「拼写=音标」，音节间用 |，短语中的词之间用 " / " 分隔。
各块的拼写连起来必须等于原词，构建时 check() 会逐个校验。

与 phon.py / phon_phy.py 同名的词不在这里重复——音标一样，构建时直接复用。
目前只有 period 属于这种情况。
"""
PHON_DAILY = {
    "deposit":     ("de=dɪ|pos=ˈpɒz|it=ɪt",
                    "de-（向下）+ posit（放置，同 position）→ 先放下一笔钱 = 押金。"),
    "paused":      ("pause=pɔːz|d=d",
                    "拉丁 pausa「停顿」；音乐里的休止符也叫 pause。"),
    "insist":      ("in=ɪn|sist=ˈsɪst",
                    "in-（在上面）+ sist（站，同 assist、resist）→ 站住不退 = 坚持。"),
    "returnable":  ("re=rɪ|turn=ˈtɜːn|a=ə|ble=bl",
                    "return（归还）+ -able（可…的）→ 可退还的。"),
    "suppose":     ("sup=sə|pose=ˈpəʊz",
                    "sub-（下面）+ pose（放置）→ 心里先垫一个假设 = 以为。"),
    "complain":    ("com=kəm|plain=ˈpleɪn",
                    "com-（加强）+ plain（拉丁 plangere 捶胸痛哭）→ 捶着胸诉苦 = 抱怨。"),
    "grumble":     ("grum=ˈɡrʌm|ble=bl",
                    "拟声词：喉咙里咕噜咕噜 → 压着嗓子嘟囔。比 complain 更小声、更持续。"),
    "tempt":       ("tempt=tempt",
                    "拉丁 temptare「试探」；同源 attempt（尝试）→ 来试探你 = 诱惑。"),
    "whine":       ("whine=waɪn",
                    "拟声：拖长的细声哼唧。和 wine（酒）同音，别写混。"),
    "lure":        ("lure=lʊə",
                    "本指驯鹰用的假饵，把鹰引回来 → 引诱。"),
    "temporary":   ("tem=ˈtem|po=pə|ra=rə|ry=ri",
                    "tempor（时间，同 tempo 节奏）+ -ary → 只占一段时间的 = 暂时的。"),
    "permanent":   ("per=ˈpɜː|ma=mə|nent=nənt",
                    "per-（自始至终）+ man（停留，同 remain）→ 一直留着 = 永久的。"),
    "lodge":       ("lodge=lɒdʒ",
                    "与 lobby（门廊）同源，本指门口的小屋 → 小屋、投宿。"),
    "halt":        ("halt=hɔːlt",
                    "德语 halten「停住」；军队口令「立定」就是 halt。"),
    "tent":        ("tent=tent",
                    "拉丁 tendere「张开」，同源 extend → 撑开的布 = 帐篷。"),
    "camp":        ("camp=kæmp",
                    "拉丁 campus「平地」→ 扎营的那片平地；校园 campus 同源。"),
    "landlord":    ("land=ˈlænd|lord=lɔːd",
                    "land（地）+ lord（主人）→ 地的主人 = 房东。"),
    "settle":      ("set=ˈset|tle=l",
                    "set（安放）+ -le → 把自己安放下来 = 定居。"),
    "sterile":     ("ste=ˈste|rile=raɪl",
                    "拉丁 sterilis「不结果实的」→ 长不出东西 = 无菌的。"),
    "polluted":    ("pol=pə|lut=ˈluːt|ed=ɪd",
                    "拉丁 polluere「玷污」→ pollute 弄脏，加 -ed = 受污染的。"),
    "drenched":    ("drench=drentʃ|ed=t",
                    "与 drink 同源，本义「灌透」→ 从外面被水灌透 = 淋透的。"),
    "parched":     ("parch=pɑːtʃ|ed=t",
                    "本指把谷物烘干 → 烤干了 = 干渴的、干旱的。正好和 drenched 相反。"),
    "gravel":      ("gra=ˈɡræ|vel=vl",
                    "与 grave（挖掘）同源 → 挖出来的碎石。"),
    "moist":       ("moist=mɔɪst",
                    "拉丁 mucidus「发霉的」→ 带水汽的；名词是 moisture 水分。"),
    "soggy":       ("sog=ˈsɒɡ|gy=i",
                    "sog（浸透）+ -y → 泡软了、烂糊糊的。"),
    "damp":        ("damp=dæmp",
                    "本义「水汽」。moist 是舒服的潮，damp 是让人不舒服的潮。"),
    "seldom":      ("sel=ˈsel|dom=dəm",
                    "古英语 seldan「稀有」→ 很少。比 rarely 更书面一点。"),
    "a lot":       ("a=ə / lot=ˈlɒt",
                    "lot 本指「一份、一批」→ 一大批 = 很多。"),
    "lists":       ("list=lɪst|s=s",
                    "本指布匹的「边条」，一条一条排下来 → 清单。"),
    "recordings":  ("re=rɪ|cord=ˈkɔːd|ings=ɪŋz",
                    "re-（再）+ cord（心，同 core）→ 再记回心里 = 记录；加 -ing 是录音。"),
    "absent":      ("ab=ˈæb|sent=sənt",
                    "ab-（离开）+ -sent（存在，同 present 在场）→ 人不在 = 缺席的。"),
    "contract":    ("con=ˈkɒn|tract=trækt",
                    "con-（共同）+ tract（拉，同 tractor 拖拉机）→ 双方拉到一起 = 合同。"),
    "propensity":  ("pro=prə|pen=ˈpen|si=sə|ty=ti",
                    "pro-（向前）+ pend（悬挂，同 pendulum 钟摆）→ 天平总往一边偏 = 倾向。"),
    "communicate": ("com=kə|mu=ˈmjuː|ni=nɪ|cate=keɪt",
                    "commun（共同，同 common）→ 把信息变成两人共同的 = 沟通。"),
    "peer":        ("peer=pɪə",
                    "拉丁 par「同等」→ 同等的人 = 同龄人、同辈；高尔夫的标准杆 par 同源。"),
    "freedom":     ("free=ˈfriː|dom=dəm",
                    "free + -dom（状态、领域，同 kingdom）→ 自由的状态。"),
    "peace":       ("peace=piːs",
                    "拉丁 pax「和平」；同源 pact（条约）→ 签了约就不打了。"),
    "reported":    ("re=rɪ|port=ˈpɔːt|ed=ɪd",
                    "re-（回）+ port（搬运，同 portable）→ 把消息搬回来 = 报道。"),
    "situation":   ("si=ˌsɪ|tu=tʃu|a=ˈeɪ|tion=ʃn",
                    "situate（使位于）+ -tion → 所处的位置 = 情况、处境。"),
}
