# -*- coding: utf-8 -*-
"""物理词表独有词汇的音节切分与词根助记。

格式与 phon.py 完全一致：值是 (音节串, 助记) 二元组，
音节串写成「拼写=音标」，音节间用 |，短语中的词之间用 " / " 分隔。
与 phon.py 同名的词不在这里重复——音标一样，构建时直接复用。
"""
PHON_PHY = {
# 一、题目指令词
"sketch": ("sketch=sketʃ", "快速画出形状、不要求精确 = 草图；考试里 sketch a graph 只要走向对。"),
"show": ("show=ʃəʊ", "展示 / 证明：show that 要求用计算或推导把结果算出来，不是写一句结论。"),
"physical quantity": ("phy=ˈfɪ|si=zɪ|cal=kl / quan=ˈkwɒn|ti=tɪ|ty=ti",
                       "physical（物理的）+ quantity（量）→ 可测量、有单位的量（时间、质量…），与纯数相对。"),
"SI unit": ("S=ˌes|I=ˈaɪ / u=ˈjuː|nit=nɪt",
            "Système International d'Unités 的缩写 → 国际单位；SI unit of mass is the kilogram。"),
# 二、测量与数据
"resolution": ("re=ˌre|so=zə|lu=ˈluː|tion=ʃn",
               "re-（再）+ solve（解开）+ -tion → 仪器能「解出」的最小变化 = 分辨率。"),
"uncertainty": ("un=ˌʌn|cer=ˈsɜː|tain=tən|ty=ti",
                "un-（不）+ certain（确定）+ -ty → 读数里说不准的那段范围 = 不确定度（±0.1 mm 之类）。"),
"error": ("er=ˈe|ror=rə", "错误 / 误差；视差、估读造成的读数偏差，和 mistake 不同——误差消不掉只能减小。"),
"parallax": ("par=ˈpæ|al=əl|lax=læks",
             "读刻度时眼睛斜看，指针好像「错位」→ 视差；正对刻度（视线垂直）可避免。"),
"reliable": ("re=rɪ|li=ˈlaɪ|a=ə|ble=bl",
             "rely（依赖）+ -able → 结果靠得住 = 可靠的；重复多次得出一致结果就可靠。"),
"accurate": ("ac=ˈæ|cu=kjʊ|rate=rət",
             "accuracy（准确）的形容词 → 接近真实值；与 precise（精密度）是考试对比送分题。"),
# 三、运动
"rest": ("rest=rest", "at rest = 静止、不动；与 motion 相对。"),
"reference point": ("ref=ˈre|er=fər|ence=əns / point=pɔɪnt",
                    "reference（参照）+ point（点）→ 描述运动时「相对哪里」移动的那个点 = 参照物。"),
"displacement": ("dis=dɪs|place=ˈpleɪs|ment=mənt",
                 "dis-（离开）+ place（放）+ -ment → 从起点直指终点的有向距离 = 位移，含方向，和 distance 不同。"),
"average speed": ("a=ˈæ|ve=və|rage=rɪdʒ / speed=spiːd",
                  "average（平均）→ 总路程 ÷ 总时间，不管中途怎么变速。"),
"constant speed": ("con=ˈkɒn|stant=stənt / speed=spiːd",
                   "con-（一起）+ stant（站）→ 一直站着不变 = 恒定速度：大小方向都不变。"),
"deceleration": ("de=ˌdiː|ce=se|le=ləˈ|ra=reɪ|tion=ʃn",
                 "de-（反向）+ acceleration（加速）→ 减速；与 acceleration 成对记。"),
"initial velocity": ("i=ɪ|ni=ˈnɪ|tial=ʃl / ve=vəˈ|lo=ˈlɒ|ci=sə|ty=ti",
                     "initium（起点，同 initial 最初的）→ 出发那一刻的速度 = 初速度 u。"),
"final velocity": ("fi=ˈfaɪ|nal=nl / ve=vəˈ|lo=ˈlɒ|ci=sə|ty=ti",
                   "fin（结束，同 finish）→ 到达那一刻的速度 = 末速度 v。"),
"distance–time graph": ("dis=ˈdɪs|tance=təns|–= / time=taɪm / graph=ɡrɑːf",
                        "横轴时间、纵轴路程；斜率就是速度。"),
"speed–time graph": ("speed=spiːd|–= / time=taɪm / graph=ɡrɑːf",
                     "横轴时间、纵轴速度；斜率是加速度，图线下方面积是路程。"),
"gradient": ("gra=ˈɡreɪ|di=di|ent=ənt",
             "grade（步、等级）+ -ient → 图线的陡峭程度 = 斜率；steeper gradient = 更大速度。"),
"stationary": ("sta=ˈsteɪ|tion=ʃn|a=ə|ry=ri",
               "与 station（车站）同源 → 停在原地不动 = 静止的。别和 stationery（文具）混。"),
# 四、力
"newton": ("new=ˈnjuː|ton=tən", "以牛顿命名；1 N = 1 kg·m/s²。力不是重量。"),
"push": ("push=pʊʃ", "把物体推离自己 = 推；和 pull（拉近）成对记。"),
"pull": ("pull=pʊl", "把物体拉向自己 = 拉；push/pull 成对记。"),
"friction": ("fric=ˈfrɪk|tion=ʃn",
             "拉丁 fricare「摩擦」→ friction 摩擦力；同源 fricative 摩擦音。"),
"air resistance": ("air=eə / re=rɪ|sis=ˈsɪs|tance=təns",
                   "空气对运动的阻碍 = 空气阻力，方向与运动方向相反。"),
"drag": ("drag=dræɡ", "拖着的感觉 = 阻力；流体里的 drag 随速度增大而增大。"),
"weight": ("weight=weɪt", "W = mg：地球把物体往下拉的力。质量 m 是 kg，重量 W 是 N，别混。"),
"gravitational field strength": ("gra=ˌɡræ|vi=vɪ|ta=ˈteɪ|tion=ʃn|al=əl / field=fiːld / strength=streŋθ",
                                 "重力场强度 g ≈ 9.8 N/kg：每千克物体受到的重力。"),
"normal contact force": ("nor=ˈnɔː|mal=ml / con=ˈkɒn|tact=tækt / force=fɔːs",
                         "normal（垂直的）→ 接触面垂直向上「顶住」物体的力 = 支持力。"),
"tension": ("ten=ˈten|sion=ʃn", "ten（伸展、拉紧）→ 绳子被拉紧时两端受的力 = 张力。"),
"resultant force": ("re=ˌrɪ|sul=ˈzʌl|tant=tənt / force=fɔːs",
                    "result（结果）→ 所有力合起来的一个净效果 = 合力；不为零就产生加速度。"),
"balanced forces": ("ba=ˈbæ|lanced=lənst / for=ˈfɔː|ces=sɪz",
                    "大小相等、方向相反、作用在同一直线 → 合力为零 = 平衡力。"),
"unbalanced forces": ("un=ˌʌn|ba=ˈbæ|lanced=lənst / for=ˈfɔː|ces=sɪz",
                      "un-（不）→ 合力不为零，物体必然变速 = 不平衡力。"),
"free fall": ("free=friː / fall=fɔːl", "只受重力、不受其他阻力的下落 = 自由落体。"),
"terminal velocity": ("ter=ˈtɜː|mi=mɪ|nal=nl / ve=vəˈ|lo=ˈlɒ|ci=sə|ty=ti",
                      "terminal（终端的）→ 重力 = 阻力时速度不再增加 = 终端速度。"),
# 五、能量、功与功率
"energy": ("e=ˈe|ner=nə|gy=dʒi", "能只会转移、转化，不会凭空产生或消失（能量守恒）。"),
"energy store": ("e=ˈe|ner=nə|gy=dʒi / store=stɔː",
                 "能量的「存放处」：动能库、重力势能库、化学能库、内能库…"),
"gravitational potential energy": ("gra=ˌɡræ|vi=vɪ|ta=ˈteɪ|tion=ʃn|al=əl / po=pə|ten=ˈten|tial=ʃl / e=ˈe|ner=nə|gy=dʒi",
                                   "物体被举高后「储存」起来的能 = 重力势能 GPE = mgh。"),
"elastic potential energy": ("e=ɪ|las=ˈlæs|tic=tɪk / po=pə|ten=ˈten|tial=ʃl / e=ˈe|ner=nə|gy=dʒi",
                             "弹簧被拉伸 / 压缩时储存的能 = 弹性势能。"),
"chemical energy": ("che=ˈke|mi=mɪ|cal=kl / e=ˈe|ner=nə|gy=dʒi",
                    "燃料、食物里以化学键形式储存的能量 = 化学能。"),
"thermal energy": ("ther=ˈθɜː|mal=ml / e=ˈe|ner=nə|gy=dʒi",
                   "therm（热，同 thermometer 温度计）→ 与温度相关的能量 = 热能 / 内能。"),
"transfer": ("trans=træns|fer=ˈfɜː",
             "trans-（越过）+ fer（带，同 ferry 渡船）→ 能量从一处「带」到另一处 = 转移。"),
"conservation of energy": ("con=ˌkɒn|ser=səˈ|va=veɪ|tion=ʃn / of=əv / e=ˈe|ner=nə|gy=dʒi",
                           "conserve（保存）→ 总能量不增不减 = 能量守恒。"),
"work done": ("work=wɜːk / done=dʌn", "W = F × s：力使物体沿力的方向移动才叫做功。"),
"joule": ("joule=dʒuːl", "以焦耳命名；1 J = 1 N·m，功和能量的单位。"),
"power": ("pow=ˈpaʊ|er=ə", "P = E ÷ t 或 W ÷ t：单位时间做的功 / 转移的能量。"),
"watt": ("watt=wɒt", "以瓦特命名；1 W = 1 J/s，功率的单位。"),
"useful energy": ("use=ˈjuːs|ful=fl / e=ˈe|ner=nə|gy=dʒi",
                  "被利用起来的能量输出（灯泡的光）→ 有用能量。"),
"wasted energy": ("wast=ˈweɪs|ed=tɪd / e=ˈe|ner=nə|gy=dʒi",
                  "没被利用、散到环境里的能量（灯泡的热）→ 浪费能量。"),
"efficiency": ("e=ɪ|ffi=ˈfɪ|cien=ʃn|cy=si",
               "useful ÷ total × 100% = 效率；能量不会凭空消失，所以永远不能超过 100%。"),
# 六、密度、压强与流体
"regular object": ("re=ˈre|gu=ɡjʊ|lar=lə / ob=ˈɒb|ject=dʒɪkt",
                   "规则物体：长宽高规整，直尺量尺寸就能算体积。"),
"irregular object": ("ir=ɪ|re=ˈre|gu=ɡjʊ|lar=lə / ob=ˈɒb|ject=dʒɪkt",
                     "ir-（不）+ regular（规则）→ 不规则物体用排水法测体积。"),
"water displacement": ("wa=ˈwɔː|ter=tə / dis=ˈdɪs|place=pleɪs|ment=mənt",
                       "把物体按进水中，溢出的水的体积 = 物体体积（排水法）。"),
"float": ("float=fləʊt", "密度比水小的物体漂在水面 = 漂浮。"),
"sink": ("sink=sɪŋk", "密度比水大的物体沉下去 = 下沉；float/sink 成对记。"),
"area": ("a=ˈeə|rea=riə", "面积；压强 = 力 ÷ 面积，同一力面积越小压强越大。"),
"pascal": ("pas=ˈpæ|cal=kl", "以帕斯卡命名；1 Pa = 1 N/m²，压强的单位。"),
"atmospheric pressure": ("at=ˌæt|mos=ˈmɒ|pher=sfə|ic=rɪk / pres=ˈpre|sure=ʃə",
                         "包围地球的空气层产生的压强 ≈ 101 kPa，向各个方向作用。"),
"liquid pressure": ("li=ˈlɪ|quid=kwɪd / pres=ˈpre|sure=ʃə",
                    "液体压强随深度增大、向所有方向作用；越深潜水耳压越大就是它。"),
"upthrust": ("up=ˈʌp|thrust=θrʌst", "up（向上）+ thrust（推）→ 流体给物体的向上推力 = 浮力。"),
# 七、热学
"thermal energy transfer": ("ther=ˈθɜː|mal=ml / e=ˈe|ner=nə|gy=dʒi / trans=træns|fer=ˈfɜː",
                           "热从高温传向低温；传导、对流、辐射三条途径。"),
"conduction": ("con=kən|duc=ˈdʌk|tion=ʃn",
               "con-（一起）+ duct（引导，同 conduct）+ -ion → 靠粒子碰撞把热传下去 = 传导，金属最擅长。"),
"convection": ("con=kən|vec=ˈvek|tion=ʃn",
               "con-（一起）+ vect（搬运）→ 流体受热上升、变冷下沉形成环流 = 对流。"),
"radiation": ("ra=ˌreɪ|di=di|a=ˈeɪ|tion=ʃn",
              "射线向外发散传热 = 热辐射；不需要介质，能穿过真空（太阳的热就是这样来的）。"),
"specific heat capacity": ("spe=spəˈ|ci=sɪ|fic=fɪk / heat=hiːt / ca=kəˈ|pa=pæ|ci=sɪ|ty=ti",
                           "specific「每单位的」+ heat capacity「储热本领」→ 每千克升高 1℃ 所需的热量。"),
# 八、波、声音与光
"transverse wave": ("trans=trænz|verse=ˈvɜːs / wave=weɪv",
                    "振动方向与传播方向垂直（光、水波）= 横波。"),
"longitudinal wave": ("lon=ˌlɒn|gi=ɡɪ|tu=ˈtjuː|di=dɪ|nal=nl / wave=weɪv",
                      "longitude（经度）→ 沿传播方向一推一拉、疏密相间（声波）= 纵波。"),
"amplitude": ("am=ˈæm|pli=plɪ|tude=tjuːd",
              "amplus（大）→ 波峰到平衡位置的距离 = 振幅，振幅越大携带能量越多。"),
"wavelength": ("wave=ˈweɪv|length=leŋθ", "两个相邻波峰（或波谷）之间的距离 = 波长 λ。"),
"period": ("pe=ˈpɪə|ri=ri|od=əd", "完成一次完整振动所需的时间 = 周期 T；频率 f = 1/T。"),
"wave speed": ("wave=ˈweɪv / speed=spiːd", "v = f × λ；波速由介质决定，不由频率决定。"),
"reflection": ("re=rɪ|flec=ˈflek|tion=ʃn",
               "re-（回）+ flect（弯，同 flexible）→ 光被「弯」回来 = 反射；入射角 = 反射角。"),
"refraction": ("re=rɪ|frac=ˈfræk|tion=ʃn",
               "re- + fract（折断，同 fracture 骨折）→ 光换介质时方向「折断」改变 = 折射。"),
"normal": ("nor=ˈnɔː|mal=ml", "法线：与镜面垂直的虚线；入射角、反射角都从法线量起。"),
"angle of incidence": ("an=ˈæŋ|gle=ɡl / of=əv / in=ˈɪn|ci=sɪ|dence=dəns",
                       "in-（朝里）+ cid（落，同 accident）→ 光线照到界面的角度 = 入射角 i。"),
"sound": ("sound=saʊnd", "声音是纵波，需要介质才能传播。"),
"vacuum": ("va=ˈvæ|cuum=kjuːəm", "vac-（空，同 vacant 空缺）→ 没有空气的空间 = 真空；声音不能在其中传播。"),
"echo": ("e=ˈe|cho=kəʊ", "声音碰到障碍物被反射回来 = 回声；声呐测距就靠它。"),
# 九、电与磁
"electric charge": ("e=ɪ|lec=ˈlek|tric=trɪk / charge=tʃɑːdʒ",
                    "带电粒子携带的电荷量，单位库仑（C）；正负电相吸、同种相斥。"),
"current": ("cur=ˈkʌ|rent=rənt", "电流 I = 单位时间流过的电荷量；单位安培 A。"),
"ampere": ("am=ˈæm|pere=peə", "以安培命名；电流的单位 A。"),
"potential difference": ("po=pə|ten=ˈten|tial=ʃl / di=ˈdɪ|ffe=fə|rence=rəns",
                         "单位电荷通过用电器时获得的能量 = 电势差 / 电压；用伏特计并联测量。"),
"circuit": ("cir=ˈsɜː|cuit=kɪt", "circ（环）→ 电流必须走一圈回到电源 = 闭合电路。"),
"series circuit": ("se=ˈsɪə|ries=riːz / cir=ˈsɜː|cuit=kɪt",
                   "把元件「串」成一条路的电路 = 串联电路，各处电流相同。"),
"parallel circuit": ("pa=ˈpæ|ral=rəl|lel=ləl / cir=ˈsɜː|cuit=kɪt",
                     "像平行线一样并排的电路 = 并联电路，各支路两端电压相同。"),
"magnetic field": ("mag=ˈmæg|ne=nə|tic=tɪk / field=fiːld",
                   "磁体周围看不见的力场；磁感线从 N 极出发回到 S 极。"),
"electromagnet": ("e=ɪ|lec=ˈlek|tro=trə|mag=ˈmæg|net=nɪt",
                  "电流一通过就显磁性、断开就消失的磁铁 = 电磁铁，可以开关。"),
"transformer": ("trans=træns|for=ˈfɔː|mer=mə",
                "trans-（变）+ form（形）→ 改变交流电压的装置 = 变压器，只能用于交流电。"),
# 十、原子核与空间物理
"nucleus": ("nu=ˈnjuː|cle=klɪ|us=əs", "原子核：由质子和中子组成，原子的质量几乎全在这里。"),
"proton": ("pro=ˈprəʊ|ton=tɒn", "带正电的粒子；质子数 = 原子序数，决定它是哪种元素。"),
"neutron": ("neu=ˈnjuː|tron=trɒn", "neutr-（中性）→ 不带电的粒子 = 中子。"),
"electron": ("e=ɪ|lec=ˈlek|tron=trɒn", "围绕原子核运行的带负电微粒 = 电子。"),
"isotope": ("i=ˈaɪ|so=sə|tope=təʊp",
            "iso-（相同）+ tope（位置）→ 质子数相同、质量数不同的原子 = 同位素，化学性质相同。"),
"radioactive decay": ("ra=ˌreɪ|di=di|o=o|ac=ˈæk|tive=tɪv / de=dɪ|cay=ˈkeɪ",
                      "原子核自发放出射线变成别的原子核 = 放射性衰变，随机、不可预测、不受外界影响。"),
"alpha particle": ("al=ˈæl|pha=fə / par=ˈpɑː|ti=tɪ|cle=kl",
                   "α 粒子 = 氦原子核（2 质子 + 2 中子），电离能力强、穿透能力弱。"),
"beta particle": ("be=ˈbiː|ta=tə / par=ˈpɑː|ti=tɪ|cle=kl",
                  "β 粒子 = 从核里射出的高速电子，穿透能力中等。"),
"gamma radiation": ("ga=ˈɡæ|mma=mə / ra=ˌreɪ|di=di|a=ˈeɪ|tion=ʃn",
                    "γ 射线是电磁波，穿透能力最强、电离能力最弱，用厚铅板才能挡住。"),
"half-life": ("half=ˈhɑːf|-=|life=laɪf", "「一半的寿命」：活度减到一半所需的时间。"),
"planet": ("pla=ˈplæ|net=nɪt", "绕恒星运行、本身不发光的巨大天体 = 行星。"),
"orbit": ("or=ˈɔː|bit=bɪt", "行星绕恒星运行的路径 = 轨道；引力提供向心力使它不掉下去也不飞走。"),
"gravitational field": ("gra=ˌɡræ|vi=vɪ|ta=ˈteɪ|tion=ʃn|al=əl / field=fiːld",
                        "有质量的物体周围产生的引力作用范围 = 重力场；太阳的重力场管着整个太阳系。"),
"star": ("star=stɑː", "自身发光发热的恒星；太阳就是一颗恒星。"),
"galaxy": ("ga=ˈɡæ|laxy=læksi", "由恒星、气体、尘埃靠引力聚成的巨大系统 = 星系；我们住在银河系 Milky Way。"),
"light-year": ("light=ˈlaɪt|-=|year=jɪə", "光一年走过的距离（是距离不是时间！）；1 光年 ≈ 9.5 万亿千米。"),
# 十一、实验技能
"risk": ("risk=rɪsk", "实验中的风险；答题要同时写出风险和处理方法（戴护目镜、远离火焰等）。"),
"safety precaution": ("safe=ˈseɪf|ty=ti / pre=prɪ|cau=ˈkɔː|tion=ʃn",
                      "pre-（预先）+ caution（小心）→ 提前做的小心 = 安全措施。"),
"valid": ("va=ˈvæ|lid=lɪd", "有效的实验：能真正回答所研究的问题、数据可支撑结论。"),
"range": ("range=reɪndʒ", "范围：自变量取较宽的范围，趋势看得更清楚、结论更有说服力。"),
"interval": ("in=ˈɪn|ter=tə|val=vl", "inter-（之间）→ 相邻两个读数之间的间隔；用相等间隔，作图更方便。"),
}
