# -*- coding: utf-8 -*-
# 每个词条: 词 -> (音节切分, 助记)
# 音节切分格式: 词与词之间用 " / " 分隔; 音节之间用 "|"; 每个音节写作 "拼写=音标"
PHON = {
# 一、指令词
"state": ("state=steɪt", "拉丁 stare「站立」→ 让答案「站出来」：只写结论，不用解释。"),
"name": ("name=neɪm", "只要「名字」：写出物质名或气体名，多写解释不得分。"),
"identify": ("i=aɪ|den=ˈden|ti=tɪ|fy=faɪ", "ident（同一、身份，同 identity）+ -ify（使…）→ 指认出「是哪一个」。"),
"define": ("de=dɪ|fine=ˈfaɪn", "de-（彻底）+ fine（界限，同 finish 的 fin）→ 划清边界 = 下定义。"),
"describe": ("de=dɪ|scribe=ˈskraɪb", "de-（往下）+ scribe（写，同 script 剧本）→ 写下所见 = 描述。"),
"explain": ("ex=ɪks|plain=ˈpleɪn", "ex-（向外）+ plain（平坦）→ 把道理「摊平」讲出来 = 解释。"),
"compare": ("com=kəm|pare=ˈpeə", "com-（共同）+ par（相等，同 pair 一对）→ 放在一起看异同。"),
"calculate": ("cal=ˈkæl|cu=kjʊ|late=leɪt", "calculus 原意「小石子」——古人用石子计数 → 计算。"),
"determine": ("de=dɪ|ter=ˈtɜː|mine=mɪn", "de- + term（界限、期限）→ 定出界限 = 确定、求出。"),
"predict": ("pre=prɪ|dict=ˈdɪkt", "pre-（预先）+ dict（说，同 dictionary）→ 预先说出 = 预测。"),
"suggest": ("sug=sə|gest=ˈdʒest", "sug-(sub 在下面) + gest（带来，同 gesture）→ 从下面递上一个合理想法。"),
"evaluate": ("e=ɪ|val=ˈvæl|u=ju|ate=eɪt", "e-（出）+ value（价值）→ 把价值说出来 = 评价优缺点。"),
# 二、科学探究与数据
"observation": ("ob=ˌɒb|ser=zə|va=ˈveɪ|tion=ʃn", "ob-（朝向）+ serve（看守）→ 盯着看 = 观察；-ation 变名词。"),
"evidence": ("e=ˈe|vi=vɪ|dence=dəns", "e-（出）+ vid（看，同 video）→ 看得出来的东西 = 证据。"),
"hypothesis": ("hy=haɪ|po=ˈpɒ|the=θə|sis=sɪs", "hypo-（在下面）+ thesis（论点）→ 垫在论点下面的「假设」。"),
"variable": ("va=ˈveə|ri=ri|a=ə|ble=bl", "vary（变化）+ -able → 会变的量 = 变量。"),
"independent variable": ("in=ˌɪn|de=dɪ|pen=ˈpen|dent=dənt / va=ˈveə|ri=ri|a=ə|ble=bl", "in-（不）+ depend（依赖）→ 不依赖别人、由你主动改变的量。"),
"dependent variable": ("de=dɪ|pen=ˈpen|dent=dənt / va=ˈveə|ri=ri|a=ə|ble=bl", "de-（向下）+ pend（悬挂，同 pendant 吊坠）→ 挂在自变量上的量 = 因变量。"),
"control variable": ("con=kən|trol=ˈtrəʊl / va=ˈveə|ri=ri|a=ə|ble=bl", "被你「控住不许动」的量；考试常问 name two control variables。"),
"fair test": ("fair=feə / test=test", "fair「公平」= 只改一个，其他全部不变。"),
"method": ("me=ˈme|thod=θəd", "meta（沿着）+ hodos（路）→ 沿着一条路走 = 方法、步骤。"),
"procedure": ("pro=prə|ce=ˈsiː|dure=dʒə", "pro-（向前）+ ceed（走，同 proceed）→ 一步步往前走 = 操作流程。"),
"result": ("re=rɪ|sult=ˈzʌlt", "re-（回）+ sult（跳，同 salt 跳跃词根）→ 事情做完「跳回来」的东西 = 结果。"),
"conclusion": ("con=kən|clu=ˈkluː|sion=ʒn", "con-（一起）+ clud（关闭，同 close）→ 把讨论关起来 = 结论。"),
"accuracy": ("ac=ˈæ|cu=kjʊ|ra=rə|cy=si", "accurate（准确）的名词。准确 = 靠近真值；和 precision 是考试送分对比题。"),
"precision": ("pre=prɪ|ci=ˈsɪ|sion=ʒn", "pre-（预先）+ cis（切，同 scissors 剪刀）→ 切得整齐 = 多次测量彼此接近。"),
"reliability": ("re=rɪ|li=ˌlaɪ|a=ə|bi=ˈbɪ|li=lə|ty=ti", "rely（依靠）→ 结果值不值得依靠 = 重复做是否一致。"),
"repeat": ("re=rɪ|peat=ˈpiːt", "re-（再）+ peat(pet 追求)→ 再做一次 = 重复。"),
"mean": ("mean=miːn", "此处不是「意思」，是「平均值」= 总和 ÷ 次数。"),
"anomalous result": ("a=ə|nom=ˈnɒm|a=ə|lous=ləs / re=rɪ|sult=ˈzʌlt", "a-（不）+ nomos（规律）→ 不合规律的点 = 异常值，作图时不连进去。"),
# 三、测量、数量与变化
"mass": ("mass=mæs", "质量，单位 g / kg；和 weight（重力）不是一回事。"),
"volume": ("vo=ˈvɒ|lume=ljuːm", "体积，单位 cm³ / dm³；量筒读数看凹液面最低处。"),
"temperature": ("tem=ˈtem|per=pər|a=ə|ture=tʃə", "temper（调和、脾气）→ 冷热的程度。口语读作 4 音节，快读常吞成 /ˈtemprətʃə/。"),
"time": ("time=taɪm", "时间，单位 s / min；速率题里几乎必出现。"),
"length": ("length=leŋθ", "long 的名词形式（long → length），结尾 -th 咬舌。"),
"distance": ("dis=ˈdɪs|tance=təns", "dis-（分开）+ stant（站）→ 两点分开站着的间隔。"),
"concentration": ("con=ˌkɒn|cen=sən|tra=ˈtreɪ|tion=ʃn", "con-（一起）+ centre（中心）→ 都挤到中心 = 浓度（也可指「专注」）。"),
"rate": ("rate=reɪt", "「每单位时间的变化量」；reaction rate、rate of change 都用它。"),
"increase": ("in=ɪn|crease=ˈkriːs", "in-（向内）+ cres（生长，同 crescent 新月渐圆）→ 增加。"),
"decrease": ("de=dɪ|crease=ˈkriːs", "de-（向下）+ cres（生长）→ 反向生长 = 减少。与 increase 成对记。"),
"remain constant": ("re=rɪ|main=ˈmeɪn / con=ˈkɒn|stant=stənt", "con-（一起）+ stant（站）→ 一直站着不动 = 保持不变（熔化时温度就是这样）。"),
"measure": ("mea=ˈme|sure=ʒə", "mea- 读 /me/ 不读 /miː/；名词 measurement = 测量值。"),
"record": ("re=rɪ|cord=ˈkɔːd", "re-（再）+ cord（心，同 cardiac）→ 再放回心里 = 记录。动词重音在后，名词 /ˈrekɔːd/ 在前。"),
"unit": ("u=ˈjuː|nit=nɪt", "uni-（一）→ 一个标准量 = 单位；答题不写单位要扣分。"),
"scale": ("scale=skeɪl", "刻度、量程，也指天平；choose a suitable scale 是作图必考。"),
# 四、物质与粒子模型
"matter": ("mat=ˈmæ|ter=tə", "占据空间、有质量的东西 = 物质；state of matter 物态。"),
"substance": ("sub=ˈsʌb|stance=stəns", "sub-（在下）+ stance（站）→ 站在现象底下的东西 = 物质本体。"),
"material": ("ma=mə|te=ˈtɪə|ri=ri|al=əl", "matter 的形容词化 → 材料，强调「用来做东西的物质」。"),
"property": ("pro=ˈprɒ|per=pə|ty=ti", "proper（本身特有的）→ 物质自带的性质，如熔点、导电性。"),
"particle": ("par=ˈpɑː|ti=tɪ|cle=kl", "part（部分）+ -icle（小）→ 极小的一份 = 粒子。"),
"atom": ("a=ˈæ|tom=təm", "a-（不）+ tom（切，同 anatomy 解剖）→ 不可再切 = 原子。"),
"molecule": ("mo=ˈmɒ|le=lɪ|cule=kjuːl", "moles（一团）+ -cule（小）→ 一小团原子 = 分子。"),
"ion": ("i=ˈaɪ|on=ən", "希腊语「走的东西」→ 带电、会向电极跑的粒子 = 离子。"),
"element": ("e=ˈe|le=lɪ|ment=mənt", "只含一种原子的纯净物 = 元素／单质；周期表上的每一格。"),
"compound": ("com=ˈkɒm|pound=paʊnd", "com-（一起）+ pound（放）→ 不同元素化学结合 = 化合物（能写化学式）。"),
"mixture": ("mix=ˈmɪks|ture=tʃə", "mix + -ture → 混合物：只是混在一起，可用物理方法分开。"),
"pure substance": ("pure=pjʊə / sub=ˈsʌb|stance=stəns", "纯净物：只有一种物质，熔沸点是一个固定值（不是范围）。"),
"solid": ("so=ˈsɒ|lid=lɪd", "固体：粒子排列紧密规则、只在固定位置振动。"),
"liquid": ("li=ˈlɪ|quid=kwɪd", "液体：粒子仍紧挨但可滑动 → 有固定体积、无固定形状。"),
"gas": ("gas=ɡæs", "气体：粒子相距很远、随机快速运动 → 可被压缩。"),
"state of matter": ("state=steɪt / of=əv / mat=ˈmæ|ter=tə", "物态：固、液、气三态；变化只改排列和运动，不改粒子本身。"),
"arrangement": ("ar=ə|range=ˈreɪndʒ|ment=mənt", "arrange（排列）+ -ment → 粒子的排列方式，答粒子模型题的关键词。"),
"motion": ("mo=ˈməʊ|tion=ʃn", "mot（动，同 motor 马达）→ 运动；粒子永不停息地运动。"),
"fixed position": ("fixed=fɪkst / po=pə|si=ˈzɪ|tion=ʃn", "固定位置：固体粒子只能在原地振动，不能换位。"),
"compress": ("com=kəm|press=ˈpres", "com-（一起）+ press（压）→ 压到一起 = 压缩；只有气体易压缩。"),
# 五、化学反应、溶液与能量
"reactant": ("re=ri|ac=ˈæk|tant=tənt", "react（反应）+ -ant（做…的物）→ 参加反应的物质，写在箭头左边。"),
"product": ("pro=ˈprɒ|duct=dʌkt", "pro-（向前）+ duct（引导，同 conduct）→ 被引出来的东西 = 生成物，在箭头右边。"),
"chemical reaction": ("che=ˈke|mi=mɪ|cal=kl / re=ri|ac=ˈæk|tion=ʃn", "化学反应：生成了新物质（常伴变色、放气、放热）。"),
"physical change": ("phy=ˈfɪ|si=zɪ|cal=kl / change=tʃeɪndʒ", "物理变化：没有新物质，通常可逆（熔化、溶解）。"),
"chemical change": ("che=ˈke|mi=mɪ|cal=kl / change=tʃeɪndʒ", "化学变化：有新物质生成，通常不易逆转。与 physical change 对照记。"),
"dissolve": ("dis=dɪ|solve=ˈzɒlv", "dis-（分开）+ solve（松开）→ 散开进溶剂里 = 溶解。ss 在这里读 /z/。"),
"solution": ("so=sə|lu=ˈluː|tion=ʃn", "solve 的名词 → 溶液 = 溶质 + 溶剂（也表示「答案」）。"),
"solute": ("so=ˈsɒ|lute=ljuːt", "被溶解的那个（盐）；-ute 结尾 = 被动的一方。"),
"solvent": ("sol=ˈsɒl|vent=vənt", "去溶解别人的那个（水）；-ent 结尾 = 主动的一方。"),
"soluble": ("so=ˈsɒ|lu=ljʊ|ble=bl", "solve + -uble（能够）→ 可溶的。"),
"insoluble": ("in=ɪn|so=ˈsɒ|lu=ljʊ|ble=bl", "in-（不）+ soluble → 不溶的；沉淀就是 insoluble 产物。"),
"saturated solution": ("sa=ˈsæ|tu=tʃə|ra=reɪ|ted=tɪd / so=sə|lu=ˈluː|tion=ʃn", "satur（充满）→ 灌满了、再也溶不下 = 饱和溶液。"),
"aqueous": ("a=ˈeɪ|que=kwi|ous=əs", "aqua（水，同 aquarium 水族馆）→ 水溶液的，方程式里写 (aq)。注意读 /ˈeɪkwiəs/。"),
"precipitate": ("pre=prɪ|ci=ˈsɪ|pi=pɪ|tate=teɪt", "pre-（向前）+ cipit（头，同 capital）→ 一头栽下去 = 沉淀。"),
"acid": ("a=ˈæ|cid=sɪd", "acid 原意「酸的」→ pH < 7，遇石蕊变红。"),
"base": ("base=beɪs", "碱（能中和酸的物质）；溶于水的碱才叫 alkali。"),
"alkali": ("al=ˈæl|ka=kə|li=laɪ", "来自阿拉伯语 al-qaly（草木灰）→ 可溶的碱，pH > 7。结尾读 /laɪ/。"),
"neutralisation": ("neu=ˌnjuː|tra=trə|li=laɪ|sa=ˈzeɪ|tion=ʃn", "neutral（中性）→ 酸 + 碱 → 盐 + 水，pH 走向 7。"),
"indicator": ("in=ˈɪn|di=dɪ|ca=keɪ|tor=tə", "indicate（指示）+ -or（物）→ 用颜色指示酸碱的东西。"),
"pH": ("p=piː|H=eɪtʃ", "读作「批-埃曲」两个字母。< 7 酸，= 7 中性，> 7 碱。"),
"catalyst": ("ca=ˈkæ|ta=tə|lyst=lɪst", "cata-（向下）+ lys（松解，同 analysis）→ 帮忙拆开、自己不变的物质。"),
"reaction rate": ("re=ri|ac=ˈæk|tion=ʃn / rate=reɪt", "反应速率：升温、增浓、加催化剂、增大表面积都会变快。"),
"collision": ("col=kə|li=ˈlɪ|sion=ʒn", "col-（一起）+ lid（撞）→ 撞在一起 = 碰撞；碰撞理论解释速率。"),
"kinetic energy": ("ki=kɪ|ne=ˈne|tic=tɪk / e=ˈe|ner=nə|gy=dʒi", "kine（运动，同 cinema 电影＝动起来的画）→ 动能，温度越高动能越大。"),
"attractive force": ("at=ə|trac=ˈtræk|tive=tɪv / force=fɔːs", "at- + tract（拉，同 tractor 拖拉机）→ 把粒子拉在一起的引力。"),
"exothermic": ("ex=ˌek|o=səʊ|ther=ˈθɜː|mic=mɪk", "exo-（向外）+ therm（热，同 thermometer）→ 热跑出来 = 放热，温度计示数升高。"),
"endothermic": ("en=ˌen|do=dəʊ|ther=ˈθɜː|mic=mɪk", "endo-（向内）+ therm（热）→ 热被吸进去 = 吸热，温度下降。与 exo- 对照记。"),
"melting": ("mel=ˈmel|ting=tɪŋ", "熔化：固 → 液，吸热；熔化过程中温度保持不变。"),
"freezing": ("free=ˈfriː|zing=zɪŋ", "凝固：液 → 固，放热；凝固点 = 熔点。"),
"boiling": ("boi=ˈbɔɪ|ling=lɪŋ", "沸腾：整个液体内部都汽化，只发生在沸点。"),
"evaporation": ("e=ɪ|va=ˌvæ|po=pə|ra=ˈreɪ|tion=ʃn", "e-（出）+ vapor（蒸气）→ 蒸气跑出去；只在表面、任何温度都能发生。"),
"condensation": ("con=ˌkɒn|den=den|sa=ˈseɪ|tion=ʃn", "con-（一起）+ dens（密）→ 变密集 = 液化；蒸气遇冷变液体。"),
"sublimation": ("sub=ˌsʌb|li=lɪ|ma=ˈmeɪ|tion=ʃn", "升华：固 → 气，跳过液态（碘、干冰）。"),
"deposition": ("de=ˌde|po=pə|si=ˈzɪ|tion=ʃn", "凝华：气 → 固，是 sublimation 的逆过程（霜的形成）。"),
# 六、实验器材、操作与安全
"apparatus": ("ap=ˌæ|pa=pə|ra=ˈreɪ|tus=təs", "ap-(ad 朝向) + para（准备）→ 备好的一套器材（不可数，问「装置」用它）。"),
"test tube": ("test=test / tube=tjuːb", "试管；tube 英音 /tjuːb/ 有个 /j/。"),
"beaker": ("bea=ˈbiː|ker=kə", "beak（鸟嘴）+ -er → 有个尖嘴的杯子 = 烧杯。"),
"conical flask": ("co=ˈkɒ|ni=nɪ|cal=kl / flask=flɑːsk", "cone（圆锥）的形容词 → 锥形瓶，方便摇晃不洒。"),
"measuring cylinder": ("mea=ˈme|su=ʒə|ring=rɪŋ / cy=ˈsɪ|lin=lɪn|der=də", "量筒：读数时视线与凹液面最低处齐平。"),
"thermometer": ("ther=θə|mo=ˈmɒ|me=mɪ|ter=tə", "therm（热）+ meter（测量器）→ 温度计。重音在 mo。"),
"balance": ("ba=ˈbæ|lance=ləns", "bi-（二）+ lanx（盘）→ 两个盘子 = 天平；更精密的天平提高 accuracy。"),
"funnel": ("fun=ˈfʌ|nel=nl", "漏斗；配合 filter paper 做过滤。"),
"filter paper": ("fil=ˈfɪl|ter=tə / pa=ˈpeɪ|per=pə", "滤纸：留下残渣 residue，滤过的液体叫 filtrate。"),
"pipette": ("pi=pɪ|pette=ˈpet", "pipe（管）+ -ette（小，法语后缀）→ 小管 = 移液管，重音在后。"),
"Bunsen burner": ("Bun=ˈbʌn|sen=sn / bur=ˈbɜː|ner=nə", "以化学家 Bunsen 命名的本生灯；蓝色火焰最热。"),
"tripod": ("tri=ˈtraɪ|pod=pɒd", "tri（三）+ pod（脚，同 podium）→ 三脚架。"),
"gauze": ("gauze=ɡɔːz", "石棉网／铁丝网，架在三脚架上让受热均匀。au 读 /ɔː/。"),
"evaporating basin": ("e=ɪ|va=ˈvæ|po=pə|ra=reɪ|ting=tɪŋ / ba=ˈbeɪ|sin=sn", "蒸发皿：把溶液蒸掉一部分水，冷却后结晶。"),
"condenser": ("con=kən|den=ˈden|ser=sə", "condense（液化）+ -er → 让蒸气变回液体的器材 = 冷凝管。"),
"heat": ("heat=hiːt", "加热（动词）；gently = 缓慢地加热。"),
"stir": ("stir=stɜː", "搅拌，用 glass rod 玻璃棒；ir 读 /ɜː/。"),
"add": ("add=æd", "加入；add slowly 缓慢加入（放热反应尤其要慢）。"),
"pour": ("pour=pɔː", "倾倒；our 在这里读 /ɔː/，不读 /aʊə/。"),
"collect": ("col=kə|lect=ˈlekt", "col-（一起）+ lect（选取，同 select）→ 收集；collect over water 排水法。"),
"filter": ("fil=ˈfɪl|ter=tə", "过滤，把不溶的固体分离出来。"),
"evaporate": ("e=ɪ|va=ˈvæ|po=pə|rate=reɪt", "蒸发（动词），名词是 evaporation。"),
"crystallise": ("crys=ˈkrɪs|tal=tə|lise=laɪz", "crystal（晶体）+ -ise（使…）→ 结晶；先蒸浓再冷却。"),
"distil": ("di=dɪ|stil=ˈstɪl", "dis-（分开）+ stil（滴落）→ 一滴滴分出来 = 蒸馏，得到纯水。"),
"dilute": ("di=daɪ|lute=ˈluːt", "di-（分开）+ lut（冲洗）→ 冲淡 = 稀释；反义 concentrated。"),
"concentrated": ("con=ˈkɒn|cen=sn|tra=treɪ|ted=tɪd", "浓的（形容词）；浓酸必须小心操作。"),
"flammable": ("flam=ˈflæ|ma=mə|ble=bl", "flame（火焰）+ -able → 易燃的。注意 inflammable 也是「易燃」，不是反义！"),
"corrosive": ("cor=kə|ro=ˈrəʊ|sive=sɪv", "cor- + rod（咬、啃，同 rodent 啮齿动物）→ 会「啃掉」东西 = 腐蚀性的。"),
"toxic": ("tox=ˈtɒk|ic=sɪk", "toxikon 原指「涂在箭上的毒」→ 有毒的；有毒气体不能吸。"),
"safety goggles": ("safe=ˈseɪf|ty=ti / gog=ˈɡɒ|gles=ɡlz", "护目镜；实验安全题的万能答案之一。"),
# 七、物理学基础词汇
"speed": ("speed=spiːd", "速率 = 距离 ÷ 时间，只有大小。"),
"velocity": ("ve=vɪ|lo=ˈlɒ|ci=sə|ty=ti", "veloc（快）→ 速度：既有大小又有方向（矢量）。"),
"acceleration": ("ac=ək|ce=ˌse|le=lə|ra=ˈreɪ|tion=ʃn", "ac- + celer（快，同 accelerator 油门）→ 速度变化的快慢 = 加速度。"),
"force": ("force=fɔːs", "力：能改变物体运动状态或形状，单位 N。"),
"gravity": ("gra=ˈɡræ|vi=vɪ|ty=ti", "grav（重）→ 重力，把物体拉向地球。"),
"pressure": ("pres=ˈpre|sure=ʃə", "press（压）+ -ure → 压强 = 力 ÷ 面积；气体压强来自粒子碰撞容器壁。"),
"density": ("den=ˈden|si=sə|ty=ti", "dense（密集）+ -ity → 密度 = 质量 ÷ 体积。"),
"electric current": ("e=ɪ|lec=ˈlek|tric=trɪk / cur=ˈkʌ|rent=rənt", "curr（流动，同 current 水流）→ 电荷的定向流动 = 电流，单位 A。"),
"voltage": ("vol=ˈvəʊl|tage=tɪdʒ", "以 Volta 命名 → 电压：每单位电荷传递的能量，单位 V。"),
"resistance": ("re=rɪ|sis=ˈzɪs|tance=təns", "re-（反）+ sist（站）→ 站着挡路 = 电阻；导线越长电阻越大。"),
"conductor": ("con=kən|duc=ˈdʌk|tor=tə", "con- + duct（引导）→ 能把电引过去 = 导体（铜、金属）。"),
"insulator": ("in=ˈɪn|su=sjʊ|la=leɪ|tor=tə", "insula（岛屿）→ 像孤岛一样不通电 = 绝缘体（塑料）。"),
"wave": ("wave=weɪv", "波：声音以波的形式传播，能量随波传递。"),
"frequency": ("fre=ˈfriː|quen=kwən|cy=si", "frequent（频繁）→ 频率，单位 Hz；频率越高音调越高。"),
"energy transfer": ("e=ˈe|ner=nə|gy=dʒi / trans=ˈtræns|fer=fɜː", "trans-（横过）+ fer（带，同 ferry 渡船）→ 能量从一处带到另一处。"),
# 八、生物与环境基础词汇
"cell": ("cell=sel", "cella（小房间）→ 细胞，生命的基本单位。"),
"tissue": ("tis=ˈtɪ|sue=ʃuː", "相似细胞组成的「一层织物」= 组织。"),
"organ": ("or=ˈɔː|gan=ɡən", "器官（心脏、肺）；由不同组织构成。"),
"organism": ("or=ˈɔː|ga=ɡə|nism=nɪzəm", "organ + -ism → 完整的生物体（细菌也算，单细胞生物）。"),
"diffusion": ("dif=dɪ|fu=ˈfjuː|sion=ʒn", "dif-（分散）+ fus（流，同 fuse 熔）→ 粒子由高浓度向低浓度净移动。"),
"osmosis": ("os=ɒz|mo=ˈməʊ|sis=sɪs", "osmos（推动）→ 渗透：只有「水」通过半透膜的移动。"),
"enzyme": ("en=ˈen|zyme=zaɪm", "en-（在内）+ zyme（酵母）→ 酶，生物催化剂，怕高温。"),
"respiration": ("res=ˌres|pi=pə|ra=ˈreɪ|tion=ʃn", "re-（反复）+ spir（呼吸，同 spirit 气息）→ 呼吸作用，从葡萄糖释放能量。"),
"photosynthesis": ("pho=ˌfəʊ|to=təʊ|syn=ˈsɪn|the=θə|sis=sɪs", "photo（光）+ syn（一起）+ thesis（放置）→ 用光把物质合起来 = 光合作用。"),
"nutrient": ("nu=ˈnjuː|tri=tri|ent=ənt", "nutri（滋养，同 nurse 护理）→ 营养物质，植物需要矿物营养。"),
"habitat": ("ha=ˈhæ|bi=bɪ|tat=tæt", "habit（居住，同 inhabit）→ 生物居住的地方 = 栖息地。"),
"population": ("po=ˌpɒ|pu=pjʊ|la=ˈleɪ|tion=ʃn", "people（人）→ 同一区域内同一物种的全部个体 = 种群。"),
"adaptation": ("a=ˌæ|dap=dæp|ta=ˈteɪ|tion=ʃn", "adapt（适应）+ -ation → 适应性特征，如厚毛皮适应寒冷。"),
"ecosystem": ("e=ˈiː|co=kəʊ|sys=sɪs|tem=təm", "eco（家、环境）+ system → 生物 + 其物理环境 = 生态系统。"),
"food chain": ("food=fuːd / chain=tʃeɪn", "食物链：箭头方向 = 能量传递方向。"),
"renewable resource": ("re=rɪ|new=ˈnjuː|a=ə|ble=bl / re=rɪ|source=ˈzɔːs", "re-（再）+ new（新）→ 能重新变新的资源（太阳能、风能）。"),
"non-renewable resource": ("non=nɒn / re=rɪ|new=ˈnjuː|a=ə|ble=bl / re=rɪ|source=ˈzɔːs", "non-（不）+ renewable → 用完就没有了（煤、石油）。"),
"pollution": ("pol=pə|lu=ˈluː|tion=ʃn", "pollut（弄脏）→ 污染；空气污染危害健康。"),
"greenhouse gas": ("green=ˈɡriːn|house=haʊs / gas=ɡæs", "温室气体（CO₂、CH₄）：像玻璃房一样把热留住。"),
"conservation": ("con=ˌkɒn|ser=sə|va=ˈveɪ|tion=ʃn", "con- + serve（保存）→ 保护物种与栖息地（也指「守恒」，如能量守恒）。"),
}
